### ISSUE TITLE
NeoForge compat

### ISSUE THREAD

**Issue by Lolothepro** [KostromDan/Mods-Decompiler-GUI#5]

**Comment by KostromDan** [comment]
Not needed since:
After 1.20.2, mods on NeoForge are not obfuscated at all.
After 1.20.6, mods on LexForge are not obfuscated at all. 
Both currently obfuscate mods at runtime using Mojmap. The mods themselves are not obfuscated, so deobfuscation is not needed.

For 1.12.2-1.20.1, use the LexForge MDK. Even if you are on NeoForge, since both using same mappings.
For 1.20.2+, don't use the deobfuscation option, since it is not needed.

**Comment by KostromDan** [comment]
Fabric mods are still obfuscated, I will think what I can do with this. Both forge mdks removed deobf option. Fabric mdk haven't got this option. So it can be a problem.
